### PR TITLE
Contributed to README.

### PR DESCRIPTION
**Pull request by davemcwave**

### CODE REVIEW

**Comment by Jerry-Thao** [comment]
I think this solution might be to inefficient. I think we need to do a BFS so we can do it in log(n) time.

**Comment by Edj209** [comment]
could you please add a description of this change, currently there is No description provided.

**Comment by davemcwave** [comment]
logn
Handling the log(n) inefficiencies, please give me a LGTM

**Comment by HelloChrisLowe** [comment]
#wontfix I don't tweet the reason

**Pull request closed without merging**
